### ISSUE TITLE
Module compilation error

### ISSUE THREAD

**Issue by mikailbala** [nf-core/seqinspector#193]
### Description of the bug

Nextflow 25.10.4 is available - Please consider updating your version to it
N E X T F L O W  ~  version 23.10.0
Pulling nf-core/seqinspector ...
WARN: Invalid config manifest attribute `contributors`
 downloaded from https://github.com/nf-core/seqinspector.git
Launching `https://github.com/nf-core/seqinspector` [jolly_mclean] DSL2 - revision: 14106c0a25 [master]
WARN: Nextflow self-contained distribution allows only core plugins -- User config plugins will be ignored: nf-core-utils@0.4.0,nf-schema@2.6.1
WARN: Invalid config manifest attribute `contributors`
ERROR ~ Module compilation error
- file : /lustre/home/gen/.nextflow/assets/nf-core/seqinspector/./workflows/seqinspector.nf
- cause: Variable `channel` already defined in the process scope @ line 206, column 27.
           softwareVersions: channel.topic("versions"),
                             ^

1 error

### Command used and terminal output

```console
nextflow run nf-core/seqinspector -profile singularity --input nf_ss.csv --outdir qc_output
```

**Comment by mikailbala** [comment]
this issue still persists but only with Nextflow vesion 23.10.0. I loaded old nextflow module on HPC by mistake, It compiles fine with Nextflow v 25.10.4

**Comment by Aratz** [comment]
Hi! According to the `nextflow.config` file, nf-core/seqinspector only supports Nextflow 25.10.2 and above. Is there any specific reason why you need to run an older version?

https://github.com/nf-core/seqinspector/blob/14106c0a25537c2224d76cde5f0f610a2cf2fd4f/nextflow.config#L406
